name: frontend_sim
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ================= CORE =================
  cupertino_icons: ^1.0.8

  # ================= API =================
  http: ^1.2.0

  # ================= STORAGE =================
  shared_preferences: ^2.2.2

  # ================= LOCATION =================
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # ================= MAP =================
  google_maps_flutter: ^2.14.0  # versi aman untuk build
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # ================= MEDIA =================
  image_picker: ^1.0.7
  permission_handler: ^12.0.1

  # ================= AUTH & UI =================
  google_sign_in: ^6.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # ================= APP ICON =================
  flutter_launcher_icons: ^0.14.4

# ================= ICON CONFIG =================
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
